-- V1: Baseline schema — identity, tenancy, and RBAC.
--
-- This migration deliberately contains NO legal-domain tables (matters, clients, documents,
-- time entries, invoices). It establishes only the load-bearing structures every later
-- migration depends on: the tenant (organizations), the actor (users), and who may do what
-- (roles / permissions). Business tables arrive in their own migrations, each of which must
-- carry its own RLS policies in the same file (see V2 and patterns/database.md).
--
-- Conventions established here and binding on every future migration:
--   * Primary keys are UUID, generated by the application, not the database.
--   * Every timestamp is TIMESTAMPTZ. There are no naive timestamps in this schema.
--   * Every tenant-scoped table carries organization_id.
--   * Every business entity table has a companion {table}_history table + trigger.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- organizations — THE TENANT
--
-- Modelled as a nested-set forest so a parent (a firm) can be granted visibility over its
-- children (offices, practice groups, acquired firms) with a single index-friendly range
-- predicate rather than a recursive query on every request. A standalone organization is a
-- tree of one: tree_root_id = id, tree_left = 1, tree_right = 2.
-- ============================================================================
CREATE TABLE organizations (
    id            UUID PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    slug          VARCHAR(100) NOT NULL,
    -- Lifecycle field. Per Engineering Principle 13 exactly one service method may ever
    -- write this column; no caller sets it inline.
    status        VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    parent_id     UUID         REFERENCES organizations (id) ON DELETE RESTRICT,
    tree_root_id  UUID         NOT NULL,
    tree_left     INTEGER      NOT NULL,
    tree_right    INTEGER      NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT organizations_slug_key UNIQUE (slug),
    CONSTRAINT organizations_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT organizations_tree_bounds_check CHECK (tree_left < tree_right)
);

CREATE INDEX idx_organizations_parent_id ON organizations (parent_id);
CREATE INDEX idx_organizations_tree ON organizations (tree_root_id, tree_left, tree_right);

-- ============================================================================
-- users — THE ACTOR
--
-- idp_sub is the Amazon Cognito `sub` claim and is the only identity join key. Email is
-- stored for display and search but is NOT an identity key: Cognito allows an email to be
-- reassigned, and matching on it would silently graft one person's history onto another.
-- organization_id is the user's primary/home organization and is nullable — a platform
-- operator belongs to no tenant.
-- ============================================================================
CREATE TABLE users (
    id              UUID PRIMARY KEY,
    idp_sub         VARCHAR(255) NOT NULL,
    email           VARCHAR(320) NOT NULL,
    full_name       VARCHAR(255),
    organization_id UUID         REFERENCES organizations (id) ON DELETE RESTRICT,
    status          VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT users_idp_sub_key UNIQUE (idp_sub),
    CONSTRAINT users_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED'))
);

CREATE UNIQUE INDEX idx_users_email_lower ON users (LOWER(email));
CREATE INDEX idx_users_organization_id ON users (organization_id);

-- ============================================================================
-- RBAC — roles, permissions, and the grants that connect them
--
-- Roles are platform-level and ranked (level). Permissions are granular capability codes
-- of the form RESOURCE:ACTION. A user's effective permission set is the union over every
-- role they hold, resolved once at authentication time into the UserPrincipal — never
-- re-derived downstream.
-- ============================================================================
CREATE TABLE roles (
    id          UUID PRIMARY KEY,
    name        VARCHAR(64) NOT NULL,
    level       INTEGER     NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE permissions (
    id          UUID PRIMARY KEY,
    code        VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT permissions_code_key UNIQUE (code),
    -- RESOURCE:ACTION, uppercase. Enforced here because a typo'd permission code fails
    -- open in the worst possible way: @RequirePermission("ORGANIZATION:READ") against a
    -- seeded "ORGANIZATIONS:READ" simply denies everyone, silently.
    CONSTRAINT permissions_code_format_check CHECK (code ~ '^[A-Z_]+:[A-Z_]+$')
);

CREATE TABLE role_permissions (
    role_id       UUID        NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id UUID        NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (role_id, permission_id)
);

-- A user's membership in an organization. Distinct from users.organization_id: that is the
-- home org, this is the full set the user may act in.
CREATE TABLE user_organizations (
    id              UUID PRIMARY KEY,
    user_id         UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    organization_id UUID        NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT user_organizations_user_org_key UNIQUE (user_id, organization_id)
);

CREATE INDEX idx_user_organizations_user_id ON user_organizations (user_id);
CREATE INDEX idx_user_organizations_organization_id ON user_organizations (organization_id);

-- A role grant. organization_id NULL means the role is global (platform-wide); non-NULL
-- scopes it to one organization. NULLS NOT DISTINCT is load-bearing: with default NULL
-- semantics the unique constraint would permit unlimited duplicate global grants.
CREATE TABLE user_roles (
    id              UUID PRIMARY KEY,
    user_id         UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id         UUID        NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    organization_id UUID        REFERENCES organizations (id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT user_roles_user_role_org_key UNIQUE NULLS NOT DISTINCT (user_id, role_id, organization_id)
);

CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_user_roles_organization_id ON user_roles (organization_id);

-- Maps a Cognito group (the `cognito:groups` claim on the access token) onto a platform
-- role. This is how identity-provider-managed groups grant roles without a manual grant
-- per user. The mapping table exists so the policy lives in data, not in a switch
-- statement (Engineering Principle 2).
CREATE TABLE cognito_group_role_mappings (
    id            UUID PRIMARY KEY,
    cognito_group VARCHAR(128) NOT NULL,
    role_id       UUID         NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT cognito_group_role_mappings_group_key UNIQUE (cognito_group)
);

-- ============================================================================
-- History tables
--
-- Every business entity table gets a {table}_history companion populated by an
-- AFTER INSERT/UPDATE/DELETE trigger. This is the platform's audit trail and the
-- data source for "who changed this, when". Reference/lookup tables (roles,
-- permissions, role_permissions) and pure junction tables are intentionally
-- excluded — they have no independent lifecycle to audit.
--
-- History columns mirror the base table exactly, but WITHOUT constraints: they store
-- snapshots, including snapshots of rows that no longer exist. The entity id column is
-- deliberately NOT a foreign key for the same reason.
-- ============================================================================
CREATE TABLE organizations_history (
    history_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID        NOT NULL,
    name            VARCHAR(255),
    slug            VARCHAR(100),
    status          VARCHAR(32),
    parent_id       UUID,
    tree_root_id    UUID,
    tree_left       INTEGER,
    tree_right      INTEGER,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ,
    change_type     VARCHAR(10) NOT NULL,
    changed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    changed_by      UUID,
    changed_by_name VARCHAR(255),
    correlation_id  UUID
);

CREATE INDEX idx_organizations_history_organization_id ON organizations_history (organization_id);
CREATE INDEX idx_organizations_history_changed_at ON organizations_history (changed_at DESC);
CREATE INDEX idx_organizations_history_correlation_id ON organizations_history (correlation_id);

CREATE TABLE users_history (
    history_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL,
    idp_sub         VARCHAR(255),
    email           VARCHAR(320),
    full_name       VARCHAR(255),
    organization_id UUID,
    status          VARCHAR(32),
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ,
    change_type     VARCHAR(10) NOT NULL,
    changed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    changed_by      UUID,
    changed_by_name VARCHAR(255),
    correlation_id  UUID
);

CREATE INDEX idx_users_history_user_id ON users_history (user_id);
CREATE INDEX idx_users_history_changed_at ON users_history (changed_at DESC);
CREATE INDEX idx_users_history_correlation_id ON users_history (correlation_id);

-- ----------------------------------------------------------------------------
-- History trigger functions.
--
-- The actor is read from session GUCs set by rls_prepare_session() (see V2). The
-- NULLIF(current_setting(..., true), '')::UUID form is mandatory: current_setting without
-- the missing_ok flag RAISES on an unset GUC, and a bare cast of '' to UUID also raises.
-- Either one would turn "nobody set an actor" into a failed write.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION record_organizations_history() RETURNS TRIGGER AS $$
DECLARE
    v_actor      UUID        := NULLIF(current_setting('app.user_id', true), '')::UUID;
    v_actor_name VARCHAR(255) := NULLIF(current_setting('app.user_name', true), '');
    v_correlation UUID       := NULLIF(current_setting('app.correlation_id', true), '')::UUID;
    v_row        organizations%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_row := OLD;
    ELSE
        v_row := NEW;
    END IF;

    INSERT INTO organizations_history (
        organization_id, name, slug, status, parent_id, tree_root_id, tree_left, tree_right,
        created_at, updated_at, change_type, changed_by, changed_by_name, correlation_id
    ) VALUES (
        v_row.id, v_row.name, v_row.slug, v_row.status, v_row.parent_id, v_row.tree_root_id,
        v_row.tree_left, v_row.tree_right, v_row.created_at, v_row.updated_at,
        TG_OP, v_actor, v_actor_name, v_correlation
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_organizations_history
    AFTER INSERT OR UPDATE OR DELETE ON organizations
    FOR EACH ROW EXECUTE FUNCTION record_organizations_history();

CREATE OR REPLACE FUNCTION record_users_history() RETURNS TRIGGER AS $$
DECLARE
    v_actor      UUID        := NULLIF(current_setting('app.user_id', true), '')::UUID;
    v_actor_name VARCHAR(255) := NULLIF(current_setting('app.user_name', true), '');
    v_correlation UUID       := NULLIF(current_setting('app.correlation_id', true), '')::UUID;
    v_row        users%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_row := OLD;
    ELSE
        v_row := NEW;
    END IF;

    INSERT INTO users_history (
        user_id, idp_sub, email, full_name, organization_id, status, last_login_at,
        created_at, updated_at, change_type, changed_by, changed_by_name, correlation_id
    ) VALUES (
        v_row.id, v_row.idp_sub, v_row.email, v_row.full_name, v_row.organization_id,
        v_row.status, v_row.last_login_at, v_row.created_at, v_row.updated_at,
        TG_OP, v_actor, v_actor_name, v_correlation
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_history
    AFTER INSERT OR UPDATE OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION record_users_history();
