package com.jurivo.backend.shared;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.domain.Persistable;

import java.util.UUID;

/**
 * Base class for entities whose primary key is a UUID generated by the application.
 *
 * <p>Spring Data JDBC decides between INSERT and UPDATE by asking whether the id is null.
 * Because Jurivo generates ids in Java (so a caller holds the identity of a row before it
 * exists, and so ids never leak insertion order), the id is always populated and every save
 * would be treated as an UPDATE of a row that does not exist — a silent no-op. Implementing
 * {@link Persistable} moves that decision onto an explicit transient flag instead.
 *
 * <p>The flag is {@code @Transient}, so it is never persisted, and is cleared after a load
 * by {@link #markNotNew()}, which the entity callback in
 * {@code com.jurivo.backend.core.config.PersistenceConfig} invokes.
 */
public abstract class BaseEntity implements Persistable<UUID> {

    @Id
    private UUID id;

    @Transient
    private boolean isNew = true;

    protected BaseEntity() {
    }

    protected BaseEntity(UUID id, boolean isNew) {
        this.id = id;
        this.isNew = isNew;
    }

    @Override
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    /** Marks this instance as already persisted, so the next save issues an UPDATE. */
    public void markNotNew() {
        this.isNew = false;
    }
}
